name: Test Azure Login
on: workflow_dispatch
permissions:
  id-token: write
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ vars.4be9dff1-14ec-4394-99be-73765be5ed5f }}
          tenant-id: ${{ vars.59bf09cd-0e7f-4322-a935-2a8c659e5d41 }}
          subscription-id: ${{ vars.e9a23062-3783-48ff-b4a8-f7814c17bd1e}}
      - run: az account show
